### ISSUE TITLE
TypeError: Cannot read property 'incomingNet' of undefined

### ISSUE THREAD

**Issue by rudyon** [lkashl/WTH#1]
I am getting the following error printed. When I try to run the application.

```
TypeError: Cannot read property 'incomingNet' of undefined
    at /home/rudyon/WTH/stats/network.js:84:52
    at Array.forEach (<anonymous>)
    at GenericTask.render (/home/rudyon/WTH/stats/network.js:81:27)
    at GenericTask.phase (/home/rudyon/WTH/classes/GenericTask.js:21:26)
    at /home/rudyon/WTH/app.js:64:27
    at async Promise.all (index 3)
    at async poll (/home/rudyon/WTH/app.js:74:9)
```

**Comment by lkashl** [comment]
Thanks for letting me know, I've committed a new build. Whilst it wont fix your issue there are a couple of benefits of this build:

- Stderr will no longer be piped into the terminal so you should only have failures isolated to your network dash section whilst the rest of the tool should work
- Debug logs are enabled and written to the ./logs directory as a text file with the name of the failing module

When you get the chance if you could run again and copy pasta the debug log that would be appreciated (./logs/network.txt)

Just as a heads up, the log contains information from your /proc/net/dev file. There isn't anything confidential here but thought I'd let you know for transparency.

**Comment by rudyon** [comment]
I have recompiled from the source and reran the application.
Here is ./logs/network.txt
```
{"adapters":["lo","11381386711"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11381387407 9106369    0   80    0     0          0      7474 463221534 4077130    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11381386711"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11381387601 9106370    0   80    0     0          0      7474 463221594 4077131    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11381386711"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11381388173 9106373    0   80    0     0          0      7474 463221774 4077134    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11381386711"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11381388791 9106377    0   80    0     0          0      7474 463222014 4077138    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391621902"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391622457 9115849    0   80    0     0          0      7496 463882052 4083579    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391621902"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391622819 9115851    0   80    0     0          0      7496 463882172 4083581    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391621902"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391623778 9115855    0   80    0     0          0      7496 463882412 4083585    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391621902"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391624253 9115858    0   80    0     0          0      7496 463882592 4083588    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391635400"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391635571 9115916    0   80    0     0          0      7496 463886786 4083647    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391635400"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391635571 9115916    0   80    0     0          0      7496 463886786 4083647    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391635400"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391635865 9115920    0   80    0     0          0      7496 463887038 4083651    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
{"adapters":["lo","11391635400"],"baseLine":{"lo":{"incoming":413376502,"outgoing":413376502}},"source":"Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed\n    lo: 413376502 6667624    0    0    0     0          0         0 413376502 6667624    0    0    0     0       0          0\nenp5s0: 11391636791 9115923    0   80    0     0          0      7496 463887218 4083654    0    0    0     0       0          0\n","_name":"network","_data":[{"incomingNet":0,"outgoingNet":0}],"_renders":[18,21]}
```
I would like to note that I can now see the application. It was previously covered by the error. The graphs seem to be fine however it seems like information is missing. Here is what is looks like.
![DeepinScreenshot_termite_20210409055545](https://user-images.githubusercontent.com/41804126/114122102-414feb00-98f8-11eb-8a22-e91b9227fa43.png)
The braille is because of the font I am using.

**Comment by lkashl** [comment]
Thanks, I'll replicate on my endanger today if I get the chance and hopefully fix the issue :)

Otherwise if you drag the windows bigger everything else should be populating :) the performance stat's are disabled at the moment but I plan to enable them after GPU polling is added

**Comment by lkashl** [comment]
Hey Rudyon, your issue should be fixed now, give the latest code a shot when you get the chance and let me know if you have any further issues :)

**Comment by rudyon** [comment]
Yes everything seems to be working as expected now. Thank you very much. I absolutely love the project it is super pretty. I have started learning node so that I can possibly contribute in the future.

**Comment by lkashl** [comment]
Great to hear!

Node is a great language, not sure how suitable it is in terms of performance for this application, but we'll see how things pan out :)
