### ISSUE TITLE
Errors throwing after trying to install (text copied from bash)

### ISSUE THREAD

**Issue by kollibroman** [lkashl/WTH#3]
> performance_monitor@1.0.0 start
> NODE_ENV=PRODUCTION node app.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kollibroman/WTH/util/file.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

please check if everything was written without errors

**Comment by lkashl** [comment]
Hey Kollibroman, it looks like the version of node that's running doesn't support the fs/promises module. 

You can upgrade node version but I'd recommend switching to the nvidia_gpu branch which implements a backwards compatibility fix. This branch will be merged into master towards the end of the week.

Let me know if you have any issues :)

EDIT: Had a chance to cherry pick the fix into the main branch as well in case you don't want to play with the nvidia branch

**Comment by lkashl** [comment]
I'll close this one out since there hasn't been any activity in over a week. Feel free to reopen the ticket if the issue hasn't been resolved!
